// @ts-nocheck
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Listen for push events from the Vercel API
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {};
  
  const title = data.title || 'אמא 50';
  const options = {
    body: data.body || 'יש משהו חדש באפליקציה!',
    icon: data.icon || '/icon-192.png',
    badge: '/icon-192.png',
    data: data.data || { url: '/' },
    dir: 'rtl'
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle clicks on the notification
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  if (event.notification.data?.url) {
    event.waitUntil(
      self.clients.openWindow(event.notification.data.url)
    );
  }
});
